# Data Lesson Map

<font color=red>Red </font> highlighted is the topic covered for this lesson

1. <font color=red>Basics Data Science and Visualisation</font>
>* <font color=red>Obtaining Data</font>
>* <font color=red>Basic Data Processing</font>
>* Basic statistics
>* Data visualization
>* Handling erroneous and missing data
2. <font color=red>Data Machine Learning Techniques</font>
>* Supervised Learning Techniques
>* Supervised Regression
>* <font color=red>Artificial Neural Networks</font>
3. AI for Data Walkthrough
>* Model Output
>* Outputs Visualisation and Validation
4. <font color=red>AI Models </font>
>* Linear Regression
>* Underfitting vs Overfitting
>* K-Nearest Neighbour (KNN)
>* Decision Tree
>* <font color=red>Convolutional Neural Networks (CNN)</font>

# Artificial Neural Networks

Have you ever wondered how we process and learn information? For example, how does our body process information such that we are able to move our hands or legs? To put it simply, the brain will process information and then send out signals to the rest of the body to trigger certain muscle movements. These signals are transported through the nervous system. One of the main components of the nervous system are neuron cells. These cells work on a threshold basis which means that the signal will only be transferred from cells to cells if it is higher than a certain value or amount. As such, when we decide to move our hands, the signals from the brain will get transferred to the muscle in our hands and not the muscle in our legs.

### Training Artificial Neural Networks
However, this only explains how we process information. How about the ability of humans to learn? For example, why do we know to stop at a red light or how to kick a ball? It is because we were trained to do so by looking at examples or how other people were doing it. Through these examples, we were able to learn and remember.

Would it be great if computers were able to mimic the way humans process and learn information? With artificial neural network, this can be done! Artificial neural networks are able to process and 'learn' complex relationships within datasets. An illustration of a simple neural network is shown below.

The basic idea is that we input data into the input layer. Data will be processed in the subsequent hidden layer(s) - we only show one hidden layer on the picture below, but it can be many layers. Each layer is made of multiple artificial neurons which apply functions to the data and pass it on to another hidden layer, finally ending with the output layer. 

![ANN](https://miro.medium.com/max/1100/1*YgJ6SYO7byjfCmt5uV0PmA.png)
Please refer to "/content/Intel_AI4Y/My Drive/Intel_AI4Y_Colab/Module_17/resources/ANN.jpg"

The illustration above shows a simple neural network with 1 input layer, 1 hidden layer (in between an input layer and an output layer) and 1 output layer. Each circle represent 1 node or 1 neuron. We usually do not discuss the number of nodes at the input layer within the model architecture as the input layer is just the data that is being passed to the model. Thus, the hidden layer has 4 nodes/neurons and the output layer has 1 node/neuron. 

The output layer will show the results of the neural network.

How does the neural network work? How can they be useful for machine learning project? Watch this [video](https://www.youtube.com/watch?v=aircAruvnKk) to find out more about artificial neural networks. Pause the video and take time to try and understand how the neural network works. Note down any interesting information on neural networks on your worksheet. Are you also able to draw out the network (similar to the illustration above) if the network has 1 input layer with 5 nodes, 2 hidden layers with 3 nodes each and 1 output layer with 2 nodes?

<font color=red>Your answer:</font> 

In [ ]:
# Neural Networks are loosely modelled after how neurons in the brain behave, they are able to automatically extract features without the help of a programmer. 
# Every neural network node/neurons is essentially a machine learning algorithm, it is useful when solving problems for large datasets.

# Training the neural network

After understanding the different features of an artificial neural network, one question that still remains is how does the network "learn"?

Take for example a young basketball player who is learning to shoot a 3-point shot. If he shoots and he misses because the shot is too short, the basketball player will adjust and increase the strength of the next shot. If the next shot now is too far right of the basket, the player will again adjust his shot to shoot more towards the center. The player continues to do this until the shot is made. The player then remembers the exact strength and shot direction when shooting 3-point shots in future.

This is similar to how neural networks are trained. First, the data is passed through the network and a predicted output is given. This is known as a forward propagation. The predicted output is then compared to the actual output of the data and the differences between the predicted and actual will be passed backwards through the model. During the backward pass, adjustments will be made within the model such that the differences between prediction output and actual output will be reduced. This is known as the backpropagation. After the adjustments are made, data will be passed through from the input layer again and another predicted output will be made. The new predicted output will be compared to the actual output again and the differences will be passed backwards through the model. More adjustments will be made within the model.

The process of forward propagation and backpropagation will be repeated until the differences between predicted output and the actual output are minimised. The model is now trained and can be used for prediction of other similar datasets.

Can you think of another example in your life that is similar to the way the neural networks are trained?

<font color=red>Your answer:</font> 

In [ ]:
# If the food you cooked is not tasty enough, you add more msg to it and taste it, and hopefully uncle roger likes it.
# I literally thought about this before even refering to the scenario below, wow...

Here is another example to help you understand neural networks better. You have been tasked to bake a cake for your father's birthday. You follow the basic cookbook and come up with a basic cake. As you want your cake to be the best cake anyone has eaten, you approach your mother for a taste test. Your mother replies that the cake is too sweet and slightly burnt. Thus, you try and adjust the amount of sugar and also the time the cake spent in the oven. Next, you will then bake another cake with your new recipe and baking time before doing another taste test with your mother. This continues until you get the perfect cake.

The first steps to bake the cake are similar to the forward propagation step within the artificial neural network. The taste test is similar to the comparison of a predicted output to the actual output. The adjustment of the amount of sugar and baking time is similar to backpropagation within the neural network. The repetition in the steps are similar to the full training process of the model.

To have a better visualisation of how backpropagation works, watch this [video](https://www.youtube.com/watch?v=Ilg3gGewQ5U) and take down any information that interests you.

<font color=green>Bonus: You are not required to understand the actual adjustments within the model. However, if you are mathematically inclined or really interested in understanding all the adjustments and have time, you can watch the 2 videos listed below. Note down any interesting information in your worksheet or the cell below. </font>
- [video 1](https://www.youtube.com/watch?v=IHZwWFHWa-w)
- [video 2](https://www.youtube.com/watch?v=tIeHLnjs5U8)

<font color=red>Your answer:</font> 

In [ ]:
# your answer here

# Training a neural network with the Iris Flower dataset

Let's try training the neural network using the Iris Flower dataset!

## 1. Import required Libraries
Firstly, we will import the required libraries: pandas and numpy to provide data structure, and scikit learn to gain access to artificial neural network. 

In [2]:
#your code here
import pandas as pd
import numpy as np 
from sklearn.preprocessing import StandardScaler

![alt text](https://www.researchgate.net/profile/Zhi-Gang_Zhao2/publication/272514310/figure/fig6/AS:340442961989646@1458179335869/Trollius-ranunculoide-flower-with-measured-traits.png)
Please refer to "/content/Intel_AI4Y/My Drive/Intel_AI4Y_Colab/Module_17/resources/PetalSepal1.png"

## 2. Obtain and explore dataset

Import the Iris Flower dataset as a dataframe df below. 
The file should be iris.data. 

Remember to include the headers for all the columns. 

Refer to the picture (source: https://www.researchgate.net/figure/Trollius-ranunculoide-flower-with-measured-traits_fig6_272514310) above to understand the variables. 

We'll first explore the data. Do you remember how this is done?
1. Open the csv file and put it into a dataframe.
2. Include headers
3. Use `.info()` and `.describe()` to see basic information about the dataset

Check for any missing values or erroneous data. Are there any missing data?

In [3]:
from google.colab import drive
drive.mount('/content/Intel_AI4Y')

Mounted at /content/Intel_AI4Y


<font color=red>Hints:</font> 


*   Refer to Module 17 Assignment 1 "Supervised_learning_techniques"in the beginning
*   Remember to print head, info and describe



In [45]:
#your code here
df = pd.read_csv("/content/Intel_AI4Y/My Drive/Intel_AI4Y/Students_E_Learning/Copy_To_Google_Drive/Intel_AI4Y_Colab/Module_17/data/iris.data",header=None)
names = ['sepal length', 'sepal width', 'petal length', 'petal width', 'class']
df.columns = names
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
       sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.50000

## 3. Determine features and target values

Now, we have to split the datset into the x values (features which the model can learn relationships from) and the y values (target values or expected output from the model). 

### Standardization
We would also have to standardize the dataset. 
What is standardization for? To understand this, look at the distribution of data above! Notice the different mean and standard deviation. Comparing between these variables will be difficult. Standardization helps us to equalize these various distributions into a common mean and standart deviation, so that we can compare them easily. Refer to the [standardscaler graph here](http://benalexkeen.com/feature-scaling-with-scikit-learn/). See how data changed before and after scaling. 


This is to allow neural networks to classify easily. The code below will extract out the x values as x_values and also standardise the values. We will extract the y_values later. Run the code below!

In [46]:
x_values = df[['sepal length','sepal width','petal length','petal width']]
print(x_values.head())
standardise = StandardScaler() # the standardscaler will transform your data such that its distribution will have a mean value 0 and standard deviation of 1
x_values = standardise.fit_transform(x_values)
x_values_df = pd.DataFrame(x_values)

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


Compare this standardized dataset to the original one

In [47]:
print(x_values_df.head())

          0         1         2         3
0 -0.900681  1.032057 -1.341272 -1.312977
1 -1.143017 -0.124958 -1.341272 -1.312977
2 -1.385353  0.337848 -1.398138 -1.312977
3 -1.506521  0.106445 -1.284407 -1.312977
4 -1.021849  1.263460 -1.341272 -1.312977


Use the .describe function to find out what is the current mean and std value of the standardized dataset!

In [48]:
print(x_values_df.describe())

                  0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -2.775558e-16 -5.140333e-16  1.154632e-16  9.251859e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.438987e+00 -1.568735e+00 -1.444450e+00
25%   -9.006812e-01 -5.877635e-01 -1.227541e+00 -1.181504e+00
50%   -5.250608e-02 -1.249576e-01  3.362659e-01  1.332259e-01
75%    6.745011e-01  5.692513e-01  7.627586e-01  7.905908e-01
max    2.492019e+00  3.114684e+00  1.786341e+00  1.710902e+00


## 4. Build the neural network

We can now build a simple neural network. In order to do so, we will need to import the dense and sequential functions from keras library. 

### Sequential
The Sequential model allows you to first create an empty model object, and then add layers to it one after another in sequence.

### Dense
A dense layer is simply a layer of neurons in the neural network. 

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Let us build a neural network with 1 input layer, 2 hidden layers and 1 output layer. There are no rules to decide how many nodes should be within the hidden layers. 

For this neural network, we will use 6 hidden nodes for each hidden layer. 

With regards to the output layer, we should use as many nodes as the number of classes. How many nodes should we use for the output?

<font color=red>Your answer:</font> 

In [ ]:
# 3 nodes because there are three classes 

Can you draw the neural network you are creating? Draw them now!

<font color=red>Your answer:</font> 

In [ ]:

#     O   O
# O   O   O
# O   O   O   O
# O   O   O   O
# O   O   O   O
#     O   O

Try the code below to build the artificial neural network.

In [50]:
# Initialise the neural network as model
model = Sequential()

# Add the first hidden layer with 6 nodes. Input_dim refers to the number of columns/number of features in x_values or the input layer.
# Activation refers to how the nodes/neurons are activated. We will use relu. Other common activations are 'sigmoid' and 'tanh'
model.add(Dense(6,input_dim=4,activation='relu'))

# Add the hidden layer with 6 nodes. 
model.add(Dense(6,activation='relu'))

# Add the output layer with 3 nodes. The activation used has to be 'softmax'. Softmax is used when you are dealing with categorical outputs or targets. 
model.add(Dense(3,activation='softmax'))

# Compile the model together. The optimizer refers to the method to make the adjustment within the model. Loss refers to how the difference between the predicted out 
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

Optional: [Comparisons between activation functions](http://www.machineintellegence.com/different-types-of-activation-functions-in-keras/)
You've learnt about ReLu earlier in Acquire-CV. There are many more activation functions. They are like [on-off buttons](https://en.wikipedia.org/wiki/Activation_function) to allow certain data/input to follow through the neurons or not. You are not expected to know the functions in detail for now. 

We can also print out the model summary after it has been compiled. Try the code below to see:
- The layers and their order in the model.
- The output shape of each layer.
- The number of parameters (weights) in each layer.
- The total number of parameters (weights) in the model.

In [51]:
model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_67 (Dense)             (None, 6)                 30        
_________________________________________________________________
dense_68 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_69 (Dense)             (None, 3)                 21        
Total params: 93
Trainable params: 93
Non-trainable params: 0
_________________________________________________________________


As the y_values are categorical in nature (categories instead of numbers), we have to convert the y_values from categories into numbers before we can train the neural network. For neural networks, if the categories are not numerical groups (for example, 1,2,3,4,etc) we have to perform label encoding (Remember doing this in an earlier notebook?) before doing one-hot encoding. Refer to the bonus section in the "Supervised learning technique" notebook for more information on one-hot encoding. You can also read this [article](https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/) to find out more. We can use the to_categorical function from Keras to help us do so. Try the code below to label encode then one-hot encode the y_values.

In [52]:
from tensorflow.keras.utils import to_categorical

# Print number of data points in each class
print(df['class'].value_counts())

# Dictionary to input the different numbers for different classes. 
# We are using values starting from 0 so that only 3 instead of 4 columns will be created in by the one-hot encoding.
label_encode = {"class": {"Iris-setosa":0, "Iris-versicolor":1, "Iris-virginica":2}}

# Use .replace to change the different classes into numbers
df.replace(label_encode,inplace=True)

# Print number of data points in each class to check if the classes have changed to numbers
print(df['class'].value_counts())

# Extract out the class as y_values
y_values = df['class']

# One-hot encode the y_values
y_values = to_categorical(y_values)

print(y_values)

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: class, dtype: int64
2    50
1    50
0    50
Name: class, dtype: int64
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1

See what is listed in the y_values above. We have encoded the flower names into numbers. 

Now, let us train the model. Run the code below!

In [53]:
# Train model with x_values and y_values. 
# Epochs refer to the number of times the full dataset will be used to train the model.
# Shuffle = True tells the model to randomise the arrangement of the dataset after each epoch. 
model.fit(x_values,y_values,epochs=20,shuffle=True)

Epoch 1/20
5/5 [==============================] - 0s 3ms/step - loss: 1.1141 - accuracy: 0.2867
Epoch 2/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0980 - accuracy: 0.2667
Epoch 3/20
5/5 [==============================] - 0s 2ms/step - loss: 1.0804 - accuracy: 0.2733
Epoch 4/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0654 - accuracy: 0.2733
Epoch 5/20
5/5 [==============================] - 0s 2ms/step - loss: 1.0507 - accuracy: 0.2533
Epoch 6/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0360 - accuracy: 0.2800
Epoch 7/20
5/5 [==============================] - 0s 2ms/step - loss: 1.0204 - accuracy: 0.3200
Epoch 8/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0065 - accuracy: 0.4133
Epoch 9/20
5/5 [==============================] - 0s 3ms/step - loss: 0.9921 - accuracy: 0.5200
Epoch 10/20
5/5 [==============================] - 0s 3ms/step - loss: 0.9791 - accuracy: 0.6067
Epoch 11/20
5/5 [======================

Well done! You have trained your first neural network. Before we look at the accuracy, we have to understand some of the terms in the output.

Epochs refer to the number of times the full dataset will be used to train the model.

us/step shows how long the model took to train on each epoch.

acc shows how accurate the model is. 

Notice how these numbers change over the different epoch.

From the model above, what was the accuracy value you've got?

Try to see if you can get a better accuracy by adding another hidden layer to the model. The additional hidden layer can have the same number of nodes as the previous layer. 

Copy the relevant codes listed above in the cell below and modify the codes to add in the additional hidden layer. Train the new model and see if the accuracy improves.

<font color=red>Hints:</font> 
*   see above code at "Try the code below to build the artificial neural network."
*   Try Insert more Dense layers.
*   Please call it `model2`
*   Remember to train the AI by calling `.fit()`: see above codes how `.fit()` is used at "Now, let us train the model. Run the code below!"







In [54]:
# Initialise the neural network as model
model2 = Sequential()

# Add the first hidden layer with 6 nodes. Input_dim refers to the number of columns/number of features in x_values or the input layer.
# Activation refers to how the nodes/neurons are activated. We will use relu. Other common activations are 'sigmoid' and 'tanh'
model2.add(Dense(6,input_dim=4,activation='relu'))

# Two hidden layers. 
model2.add(Dense(6,activation='relu')) # relu stands for rectified linear unit
model2.add(Dense(6,activation='relu')) 

# Add the output layer with 3 nodes. The activation used has to be 'softmax'. Softmax is used when you are dealing with categorical outputs or targets. 
model2.add(Dense(3,activation='softmax'))

# Compile the model together. The optimizer refers to the method to make the adjustment within the model. Loss refers to how the difference between the predicted out 
model2.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])


model2.summary()

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_70 (Dense)             (None, 6)                 30        
_________________________________________________________________
dense_71 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_72 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_73 (Dense)             (None, 3)                 21        
Total params: 135
Trainable params: 135
Non-trainable params: 0
_________________________________________________________________


In [55]:
model2.fit(x_values,y_values,epochs=20,shuffle=True)

Epoch 1/20
5/5 [==============================] - 0s 3ms/step - loss: 1.1355 - accuracy: 0.3333
Epoch 2/20
5/5 [==============================] - 0s 3ms/step - loss: 1.1179 - accuracy: 0.3333
Epoch 3/20
5/5 [==============================] - 0s 3ms/step - loss: 1.1030 - accuracy: 0.3267
Epoch 4/20
5/5 [==============================] - 0s 5ms/step - loss: 1.0877 - accuracy: 0.3133
Epoch 5/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0733 - accuracy: 0.3067
Epoch 6/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0590 - accuracy: 0.2933
Epoch 7/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0454 - accuracy: 0.3133
Epoch 8/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0328 - accuracy: 0.3467
Epoch 9/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0203 - accuracy: 0.4067
Epoch 10/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0085 - accuracy: 0.4667
Epoch 11/20
5/5 [======================

After adding another hidden layer, you should observe that the accuracy seems to be lower than the initial model. As such, this shows that adding more layers need not necessarily lead to a higher accuracy.

<font color = green>Bonus: You can try other methods to improve the accuracy. How about increasing the number of nodes in the hidden layer? Do you get a higher accuracy if you do so?</font>

<font color=red>Hints:</font> 
*   see above code at "Try the code below to build the artificial neural network." with more layers by increase the number in Dense
*   Try Insert more Dense layers.
*   Please call it model2
*   Remember to train the AI by calling `.fit()`: see above codes how `.fit()` is used at "Now, let us train the model. Run the code below!"


In [56]:
# Initialise the neural network as model
model3 = Sequential()

# Add the first hidden layer with 6 nodes. Input_dim refers to the number of columns/number of features in x_values or the input layer.
# Activation refers to how the nodes/neurons are activated. We will use relu. Other common activations are 'sigmoid' and 'tanh'
model3.add(Dense(6,input_dim=4,activation='relu'))

# 3 hidden layers . 
model3.add(Dense(6,activation='relu')) # relu stands for rectified linear unit
model3.add(Dense(6,activation='relu'))
model3.add(Dense(6,activation='relu'))  

# Add the output layer with 3 nodes. The activation used has to be 'softmax'. Softmax is used when you are dealing with categorical outputs or targets. 
model3.add(Dense(3,activation='softmax'))

# Compile the model together. The optimizer refers to the method to make the adjustment within the model. Loss refers to how the difference between the predicted out 
model3.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])


model3.summary()

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_74 (Dense)             (None, 6)                 30        
_________________________________________________________________
dense_75 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_76 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_77 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_78 (Dense)             (None, 3)                 21        
Total params: 177
Trainable params: 177
Non-trainable params: 0
_________________________________________________________________


In [57]:
model3.fit(x_values,y_values,epochs=20,shuffle=True)

Epoch 1/20
5/5 [==============================] - 1s 3ms/step - loss: 1.0920 - accuracy: 0.3933
Epoch 2/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0854 - accuracy: 0.3933
Epoch 3/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0766 - accuracy: 0.4000
Epoch 4/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0677 - accuracy: 0.4067
Epoch 5/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0575 - accuracy: 0.4267
Epoch 6/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0458 - accuracy: 0.4400
Epoch 7/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0354 - accuracy: 0.4600
Epoch 8/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0224 - accuracy: 0.4800
Epoch 9/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0105 - accuracy: 0.5067
Epoch 10/20
5/5 [==============================] - 0s 3ms/step - loss: 0.9985 - accuracy: 0.5200
Epoch 11/20
5/5 [======================

<font color=red>Your answer:</font> 

In [ ]:
# Even better acc with more dense layer

# Validation Dataset

From the above, we can see that the neural network can be trained for any number of epochs. This means that the network can keep learning from the same dataset many times. What do you think will happen if the model keeps learning from the same dataset? Do you think the network will be able to obtain very high accuracy by doing so?

<font color=red>Your answer:</font> 

In [ ]:
# Yes, increasing the number of epochs could reduce the model perplexity

You were right if you think that the model's accuracy will increase as it continues to learn. You can try it on the same dataset. Run the code below and observe the accuracy. Is it higher than the accuracy from the previous model with the same setting?

In [58]:
# Initialise the neural network as model
model4 = Sequential()

# Add the first hidden layer with 6 nodes. Input_dim refers to the number of columns/number of features in x_values or input_layer.
# Activation refers to how the nodes/neurons are activated. We will use relu. Other common activations are 'sigmoid' and 'tanh'
model4.add(Dense(6,input_dim=4,activation='relu'))

# Add the hidden layer with 6 nodes. 
model4.add(Dense(6,activation='relu'))

# Add the output layer with 3 nodes. The activation used has to be 'softmax'. Softmax is used when you are dealing with categorical outputs or targets. 
model4.add(Dense(3,activation='softmax'))

# Compile the model together. The optimizer refers to the method to make the adjustment within the model. Loss refers to how the difference between the predicted out 
model4.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# Train model with x_values and y_values. Epochs refer to the number of times the full dataset will be used to train the model.
# Shuffle = True tells the model to randomise the arrangement of the dataset after each epoch. This will allow the model to learn.
model4.fit(x_values,y_values,epochs=200,shuffle=True)

Epoch 1/200
5/5 [==============================] - 0s 3ms/step - loss: 1.0972 - accuracy: 0.1400
Epoch 2/200
5/5 [==============================] - 0s 4ms/step - loss: 1.0738 - accuracy: 0.1400
Epoch 3/200
5/5 [==============================] - 0s 3ms/step - loss: 1.0522 - accuracy: 0.3333
Epoch 4/200
5/5 [==============================] - 0s 4ms/step - loss: 1.0307 - accuracy: 0.5000
Epoch 5/200
5/5 [==============================] - 0s 4ms/step - loss: 1.0107 - accuracy: 0.4933
Epoch 6/200
5/5 [==============================] - 0s 4ms/step - loss: 0.9918 - accuracy: 0.5333
Epoch 7/200
5/5 [==============================] - 0s 3ms/step - loss: 0.9731 - accuracy: 0.5733
Epoch 8/200
5/5 [==============================] - 0s 4ms/step - loss: 0.9546 - accuracy: 0.6200
Epoch 9/200
5/5 [==============================] - 0s 3ms/step - loss: 0.9370 - accuracy: 0.7000
Epoch 10/200
5/5 [==============================] - 0s 5ms/step - loss: 0.9205 - accuracy: 0.7400
Epoch 11/200
5/5 [===========

You can observe from the printout that the accuracy score is now above 90%. Wow! It seems amazing that just increasing the number of epochs will allow the accuracy to increase. Do you think it is good that the model is so highly accuracte on the data that it has trained on? Just imagine, will a soccer player do well in a match if he/she only trains extremely hard on scoring a goal from a specific spot on the field? Or will a baker be able to bake a delicious cake based on a customer's request if he/she only learns how to bake a cake that is a specific flavour, shape and size?

The soccer player will not perform well in a match as he/she may not be able to shoot accurately from other parts of the field. The baker will not be able to bake a delicious cake as he/she will only know 1 specific flavour.

The idea behind this question is the concept of overfitting. If the model overfits, it will not be able to generalise to properly predict data that it has not seen before.

This is the concept of overfitting and also applies to all machine learning techniques. Once the technique has fitted too acurrately on the dataset, the trained technique will not be able to generalise to other data that it has not seen before. As such, we usually only train the technique on a fraction of the dataset that we have and keep the remainder as a test or validation set to see if the model has overfitted. When training on the training set, the accuracy of the model on the test set should increase. However, at the point of overfitting, the accuracy on the test set will start to decrease. If you see that the test accuracy has begin to increase after a certain epoch, you should not train the model any further.

Let us apply the split between a train and a test set to the dataset that we are using here.

First, we need to decide how much data we want to keep and prevent the model from training on. Usually, we withold about 20% to 30% of the dataset. In this example, we will keep 25 percent of the dataset as the test/validation set. We can use the train_test_split function from the sklearn library. Try the code below.

In [62]:
from sklearn.model_selection import train_test_split

# Extract out original x_values from the dataframe df. 
# We have to re-extract the x_values as the standardisation should only be based on the data that the model will train with.
# Thus, we have to split the data first before standardising.
x_values = df[['sepal length','sepal width','petal length','petal width']]

# Test_size=0.25 indicates that 25% of the datapoints will be in x_test and y_test whereas 75% will be in x_train and y_train.
# random_state=10 is used to ensure that the split is the same everytime you run the code below. 
# This is because the split is done randomly everytime. The same random_state is the only way to ensure the same split everytime.
x_train, x_test, y_train, y_test = train_test_split(x_values,y_values,test_size=0.25,random_state=10)

# Check the number of rows in x_train, x_test, y_train and y_test
print("Number of rows in x_train:", x_train.shape[0])
print("Number of rows in x_test:", x_test.shape[0])
print("Number of rows in y_train:", y_train.shape[0])
print("Number of rows in y_test:", y_test.shape[0])

# We can now standardise the x values.
# Initialise the StandardScaler
standardise = StandardScaler()

# Standardise the x_train values using .fit_transform
x_train = standardise.fit_transform(x_train)

# Standardise the x_test values using .transform. 
# There is no need to fit the data as the standardisation should be the same as that of x_train.
x_test = standardise.transform(x_test)

Number of rows in x_train: 112
Number of rows in x_test: 38
Number of rows in y_train: 112
Number of rows in y_test: 38


Write your own code to split the dataset into train and test/validation sets by witholding 20% of the dataset as test/validation set. Use `x_train2`, `x_test2`, `y_train2` and` y_test2` as your variables. Check that the number of rows are correct for each variable.


<font color=red>Hint:</font> 
 similar to above code but use `x_train2`, `x_test2`, `y_train2` and `y_test2` as your variables.

In [65]:
from sklearn.model_selection import train_test_split

x_values = df[['sepal length', 'sepal width', 'petal length', 'petal width']]

x_train, x_test, y_train, y_test = train_test_split(x_values, y_values, test_size=0.2, random_state=10)

print("Number of rows in x_train:", x_train.shape[0])
print("Number of rows in x_test:", x_test.shape[0])
print("Number of rows in y_train:", y_train.shape[0])
print("Number of rows in y_test:", y_test.shape[0])

standardise = StandardScaler()

x_train = standardise.fit_transform(x_train)

x_test = standardise.transform(x_test)

Number of rows in x_train: 120
Number of rows in x_test: 30
Number of rows in y_train: 120
Number of rows in y_test: 30


We shall now use `x_train2`, `x_test2`, `y_train2` and `y_test2` to train a neural network. Write a code to create a neural network that has 2 hidden layers with 6 nodes each and 1 output layer with 3 nodes. The activation for the input hidden layer is '`relu`' wheras the activation for the output layer is '`softmax`'. The opitmizer to use is '`adam`' and the loss should be '`categorical_crossentropy`'. The metrics should be '`accuracy`'. Use model_val as the model variable. Print the model summary after you compile the model.

<font color=red>Hint:</font> 

*   refer to the above codes at "Try the code below to build the artificial neural network."
*   Please name your model as `model_val`
*   Print the model summary after you compile the model.




In [66]:
model_val = Sequential()
# Input layer 
model_val.add(Dense(6,input_dim=4,activation='relu'))

# Hidden layer 1 
model_val.add(Dense(6, activation='relu'))

# Hidden layer 2
model_val.add(Dense(6, activation='relu'))

# Output layer
model_val.add(Dense(3, activation='softmax'))

# compile
model_val.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model_val.summary()

Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_82 (Dense)             (None, 6)                 30        
_________________________________________________________________
dense_83 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_84 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_85 (Dense)             (None, 3)                 21        
Total params: 135
Trainable params: 135
Non-trainable params: 0
_________________________________________________________________


We can now train model_val using `x_trai`n and `y_train`. We will also test the accuracy after each epoch using `x_test` and `y_test`. Try the code below!

In [67]:
# Train model with x_values and y_values. 
# Epochs refer to the number of times the full dataset will be used to train the model.
# Shuffle = True tells the model to randomise the arrangement of the dataset after each epoch. This will allow the model to learn.
# Validation_data will allow us to input in the test/validation datasets. This will allow us to see the model accuracy on the test/validation set.
model_val.fit(x_train,y_train,epochs=50,shuffle=True,validation_data=(x_test,y_test))

Epoch 1/50
4/4 [==============================] - 1s 73ms/step - loss: 1.1591 - accuracy: 0.3083 - val_loss: 1.1247 - val_accuracy: 0.4000
Epoch 2/50
4/4 [==============================] - 0s 9ms/step - loss: 1.1355 - accuracy: 0.2750 - val_loss: 1.1089 - val_accuracy: 0.4000
Epoch 3/50
4/4 [==============================] - 0s 10ms/step - loss: 1.1154 - accuracy: 0.2167 - val_loss: 1.0937 - val_accuracy: 0.3333
Epoch 4/50
4/4 [==============================] - 0s 9ms/step - loss: 1.0945 - accuracy: 0.2000 - val_loss: 1.0796 - val_accuracy: 0.2333
Epoch 5/50
4/4 [==============================] - 0s 13ms/step - loss: 1.0738 - accuracy: 0.1917 - val_loss: 1.0662 - val_accuracy: 0.2000
Epoch 6/50
4/4 [==============================] - 0s 11ms/step - loss: 1.0556 - accuracy: 0.2167 - val_loss: 1.0535 - val_accuracy: 0.2000
Epoch 7/50
4/4 [==============================] - 0s 12ms/step - loss: 1.0378 - accuracy: 0.2500 - val_loss: 1.0426 - val_accuracy: 0.2000
Epoch 8/50
4/4 [=============

Did you notice that the printout now shows the validation accuracy as well? Is the validation accuracy higher or lower than the training accuracy?

<font color=red>Your answer:</font> 

In [ ]:
# Lower 

We can also use the model to identify flower types for newly gathered data. For example, imagine that your friend has measured the sepal_length, sepal_width, petal_length and petal_width of some flowers and saved the data in a file called "iris_predict.data". Your friend wants to find the flower types for these flowers based on the values measured. Would you be able to use your model to help your friend? What are the flower types that your friend measured? Try the codes below!

<font color=red>Hint: You can use model.predict method to obtain the flower types for your friend. Additionally, the values returned by the .predict method will be the probability of each flower type that the model thinks should be assigned to each data row. As such, the higher the probablity, the more confident the model is that the flower type predicted is correct. For example, if the predicted values are very high in the second column, then the model thinks that the flower type is versicolor. You will also need to scale your data before obtaining the flower types. </font>

In [68]:
df2 = pd.read_csv("/content/Intel_AI4Y/My Drive/Intel_AI4Y/Students_E_Learning/Copy_To_Google_Drive/Intel_AI4Y_Colab/Module_17/iris_predict.data",header=None)
names = ["sepal_length", "sepal_width","petal_length", "petal_width"]
df2.columns = names

In [69]:
x_new = df2[['sepal_length','sepal_width','petal_length','petal_width']]

In [70]:
x_new_scale = standardise.transform(x_new)

In [71]:
y_new = model_val.predict(x_new_scale)

In [72]:
print(y_new)

[[0.398489   0.32016078 0.2813502 ]
 [0.36959013 0.35034534 0.2800645 ]
 [0.39731008 0.32136554 0.28132436]
 [0.05446571 0.24432164 0.7012127 ]
 [0.27277344 0.4617394  0.2654872 ]
 [0.02667199 0.2624075  0.7109205 ]
 [0.00530445 0.10167564 0.89301986]
 [0.0090673  0.12415619 0.8667765 ]
 [0.02861563 0.24671684 0.72466755]
 [0.22851314 0.456077   0.31540984]]


What are the flower types for each data row? You can use the [argmax](https://www.geeksforgeeks.org/numpy-argmax-python/) function to help you identify the flower types from `y_new`. Try the code below!

In [73]:
flower_types = []
for ii in range(0,y_new.shape[0]):
    flower_types.append(np.argmax(y_new[ii,:]))
print(flower_types)

[0, 0, 0, 2, 1, 2, 2, 2, 2, 1]


Are you able to match the flower type numbers back to the different types (Setosa, Versicolor, Virginica)?

<font color=red>Your answer:</font> 

In [ ]:
# ['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-vericolor', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-vericolor']

Congrats! You have successfully learnt how to create an artificial neural network model and trained it. Artficial neural networks are extremely powerful tools that can be used on very large datasets. For example, if you have a couple of hundred columns/features and over 100000 data points, it may be beneficial to use artificial neural networks instead of other machine learning techniques. Just remember, there are no strict rules on the number of nodes in the hidden layer or the number of hidden layers. Experiment with different neural networks to see which one provides the best result for your dataset.